{{- if and .Values.chap.enabled (not .Values.chap.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iscsi-longhorn.chapSecretName" . }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.chap.username | quote }}
  password: {{ .Values.chap.password | quote }}
{{- end }}
