apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-target-vol
  namespace: iscsi-target
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block          # raw block — not a filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi         # adjust to your needs
